/**
 * 
 */
package com.github.pfmiles.dstier1.impl;

import java.util.List;

import org.apache.commons.lang3.tuple.Pair;

/**
 * Encapsulates values, provides a reference to manage them. Used in store
 * values during a request/response progress.
 * 
 * @author pf-miles
 *
 */
public class ValueHolder {
	/**
	 * from which the site mapping, it's the original requesting site in the request
	 */
	private String fromSite;
	/**
	 * to which the site mapped, it's generated by the configured site mapping
	 * manager
	 */
	private String toSite;
	/**
	 * tell if the current request/response needs filtering
	 */
	private boolean needFiltering;
	/**
	 * filter methods for this request process
	 */
	private Pair<List<SortableFilterMethod>, List<SortableFilterMethod>> filterMethods;

	public Pair<List<SortableFilterMethod>, List<SortableFilterMethod>> getFilterMethods() {
		return filterMethods;
	}

	public void setFilterMethods(Pair<List<SortableFilterMethod>, List<SortableFilterMethod>> filterMethods) {
		this.filterMethods = filterMethods;
	}

	public boolean isNeedFiltering() {
		return needFiltering;
	}

	public void setNeedFiltering(boolean needFiltering) {
		this.needFiltering = needFiltering;
	}

	public String getFromSite() {
		return fromSite;
	}

	public void setFromSite(String fromSite) {
		this.fromSite = fromSite;
	}

	public String getToSite() {
		return toSite;
	}

	public void setToSite(String toSite) {
		this.toSite = toSite;
	}

}
